# traefik-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  selector:
    app: traefik
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080 # NodePort for HTTP
  - name: https
    port: 443
    targetPort: 443
    nodePort: 30443 # NodePort for HTTPS
  - name: dashboard
    port: 8080 # Expose the Traefik dashboard on NodePort
    targetPort: 8080
    nodePort: 32080 # Fixed NodePort for Traefik dashboard (choose an available port)
  type: NodePort
