apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus
  namespace: apps
data:
  config.yaml: |
    metrics: true
    endpoints:
      - name: ExternalSecrets
        url: tcp://external-secrets-webhook.external-secrets.svc.cluster.local:443
        interval: 5m
        conditions:
          - "[CONNECTED] == true"
      - name: Authentik
        url: http://authentik.apps.svc.cluster.local:80
        interval: 5m
        conditions:
          - "[CONNECTED] == true"
      - name: PostgreSQL
        url: tcp://authentik-postgresql.apps.svc.cluster.local:5432
        interval: 5m
        conditions:
          - "[CONNECTED] == true"
      - name: Redis
        url: tcp://authentik-redis-master.apps.svc.cluster.local:6379
        interval: 5m
        conditions:
          - "[CONNECTED] == true"
      - name: MariaDB
        url: tcp://mariadb.apps.svc.cluster.local:3306
        interval: 5m
        conditions:
          - "[CONNECTED] == true"
      - name: MyAAC
        url: http://website.apps.svc.cluster.local:80
        interval: 5m
        conditions:
          - "[STATUS] == 200"
      - name: phpMyAdmin
        url: http://phpmyadmin.apps.svc.cluster.local:80
        interval: 5m
        conditions:
          - "[CONNECTED] == true"
      - name: Prometheus
        url: http://prometheus.apps.svc.cluster.local:9090
        interval: 5m
        conditions:
          - "[CONNECTED] == true"
