apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus
  namespace: apps
data:
  config.yaml: |
    metrics: true
    endpoints:
    - name: ExternalSecrets
      group: Secrets
      url: tcp://external-secrets-webhook.external-secrets.svc.cluster.local:443
      interval: 5m
      conditions:
        - "[CONNECTED] == true"
    
    - name: Authentik
      group: Authentication
      url: http://authentik.apps.svc.cluster.local:80
      interval: 5m
      conditions:
        - "[CONNECTED] == true"

    - name: PostgreSQL
      group: Authentication
      url: tcp://authentik-postgresql.apps.svc.cluster.local:5432
      interval: 5m
      conditions:
        - "[CONNECTED] == true"

    - name: Redis
      group: Authentication
      url: tcp://authentik-redis-master.apps.svc.cluster.local:6379
      interval: 5m
      conditions:
        - "[CONNECTED] == true"

    - name: MariaDB
      group: Tibia
      url: tcp://mariadb.apps.svc.cluster.local:3306
      interval: 5m
      conditions:
        - "[CONNECTED] == true"

    - name: MyAAC
      group: Tibia
      url: http://website.apps.svc.cluster.local:80
      interval: 5m
      conditions:
        - "[STATUS] == 200"

    - name: Tibia Server (Game)
      group: Tibia
      url: tcp://tibia.apps.svc.cluster.local:7171
      interval: 5m
      conditions:
        - "[CONNECTED] == true"

    - name: Tibia Server (Login)
      group: Tibia
      url: tcp://tibia.apps.svc.cluster.local:7172
      interval: 5m
      conditions:
        - "[CONNECTED] == true"

    - name: phpMyAdmin
      group: Tibia
      url: http://phpmyadmin.apps.svc.cluster.local:80
      interval: 5m
      conditions:
        - "[CONNECTED] == true"

    - name: Prometheus
      group: Monitoring
      url: http://kube-prometheus-stack-prometheus.apps.svc.cluster.local:9090
      interval: 5m
      conditions:
        - "[CONNECTED] == true"

    - name: Grafana
      group: Monitoring
      url: http://kube-prometheus-stack-grafana.apps.svc.cluster.local:80
      interval: 5m
      conditions:
        - "[CONNECTED] == true"

    - name: Alertmanager
      group: Monitoring
      url: http://alertmanager-operated.apps.svc.cluster.local:9093
      interval: 5m
      conditions:
        - "[CONNECTED] == true"

    - name: Kube Metrics
      group: Monitoring
      url: http://kube-prometheus-stack-kube-state-metrics.apps.svc.cluster.local:8080/metrics
      interval: 5m
      conditions:
        - "[CONNECTED] == true"
