apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus
  namespace: apps
data:
  config.yaml: |
    metrics: true
    endpoints:
      - name: GitHub
        url: https://api.github.com/healthz
        interval: 5m
        conditions:
          - "[STATUS] == 200"
      - name: MariaDB
        url: tcp://mariadb.apps.svc.cluster.local:3306
        interval: 5m
        conditions:
          - "[CONNECTED] == true"
      - name: MyAAC
        url: http://website.apps.svc.cluster.local:80
        interval: 5m
        conditions:
          - "[STATUS] == 200"
