apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - configmap.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
