apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc-grafana
  namespace: apps
  labels:
    name: pvcgrafana
spec:    
  accessModes:
  - ReadWriteOnce
  resources:
    requests:   
      storage: 5Gi
