apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc-prometheus
  namespace: apps
  labels:
    name: pvcprometheus
spec:    
  accessModes:
  - ReadWriteOnce
  resources:
    requests:   
      storage: 5Gi
