apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: my-secret-store
  namespace: external-secrets
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.ap-sydney-1.fntp3zjnaafru.abzxsljrzcphia56vbn5kfln36xi7yrz6jh4b2izwznnlokdmhmfbqgjrufq
      region: ap-sydney-1
      principalType: InstancePrincipal
