apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: my-secret-store
  namespace: external-secrets
spec:
  provider:
    oracle:
      vault: ${vault_ocid}
      region: ap-sydney-1
      principalType: InstancePrincipal
