# kubernetes/traefik/ingressroute.yml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
  namespace: traefik
spec:
  entryPoints:
  - dashboard
  routes:
  - match: PathPrefix(`/dashboard`)
    kind: Rule
    services:
    - name: dashboard
      port: 8081
