---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secret
  namespace: apps
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: my-secret-store
    kind: ClusterSecretStore
  target:
    name: authentik
    creationPolicy: Owner
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: authentik_secret_key
    - secretKey: AUTHENTIK_BOOTSTRAP_PASSWORD
      remoteRef:
        key: authentik_bootstrap_password
    - secretKey: AUTHENTIK_BOOTSTRAP_TOKEN
      remoteRef:
        key: authentik_bootstrap_token
    - secretKey: POSTGRESQL_PASSWORD
      remoteRef:
        key: authentik_postgresql_password
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: authentik_redis_password
