apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tibia
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: tibia
  targetNamespace: apps
