# flux/apps.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 10m
  path: "./kubernetes/apps/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: default
