# external-secrets/deployment.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-crds
  namespace: flux-system
spec:
  interval: 5m
  path: ./deploy/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  releaseName: external-secrets
  targetNamespace: external-secrets
  interval: 5m
  chart:
    spec:
      chart: external-secrets
      version: 0.10.3
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    installCRDs: false
  install:
    createNamespace: true
    remediation:
      retries: 3
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-secretstore
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-crds
  interval: 2m
  path: ./kubernetes/base/external-secrets/stores
  prune: true
  sourceRef:
    kind: GitRepository
    name: tibia
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: external-secrets
      namespace: flux-system
    - apiVersion: v1
      kind: Service
      name: external-secrets-webhook
      namespace: external-secrets
    - apiVersion: v1
      kind: Endpoints
      name: external-secrets-webhook
      namespace: external-secrets
  postBuild:
    substituteFrom:
      - kind: Secret
        name: oracle-vault-config
        optional: false
