---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authelia-secrets
  namespace: apps
spec:
  dependsOn:
    - name: external-secrets-secretstore
      namespace: flux-system
  interval: 5m
  path: ./kubernetes/apps/authelia/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: tibia
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authelia-deploy
  namespace: apps
spec:
  dependsOn:
    - name: mariadb-post-deploy
  interval: 5m
  path: ./kubernetes/apps/authelia/deploy
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: tibia
    namespace: flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: authelia
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.authelia.com/
