# authelia/deploy/release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: apps
spec:
  releaseName: authelia
  chart:
    spec:
      chart: authelia
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: apps
      version: "0.9.9"
  interval: 5m
  values:
    image:
      registry: docker.io
      repository: authelia/authelia
      tag: "4.38"
    redis:
      enabled: true
    secret:
      existingSecret: authelia
    storage:
      mysql:
        enabled: true
        host: mariadb.apps.svc.cluster.local
        port: 3306
        database: ${authelia-mariadb-database}
        username: ${authelia-mariadb-user}
        password: ${authelia-mariadb-password}
    authentication:
      backend: file
    # jwt_secret: ${authelia-token}
    # storageEncryptionKey: ${authelia-encryption-key}
