---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: apps
spec:
  dependsOn:
    - name: external-secrets-secretstore
      namespace: flux-system
  path: ./kubernetes/apps/observability/release
  interval: 30m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: tibia
    namespace: flux-system
  # retryInterval: 1m
  # timeout: 15m
  # postBuild:
  #   substitute:
  #     THANOS_VERSION: v0.34.1
