---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: apps
spec:
  type: oci
  interval: 5m
  url: oci://ghcr.io/prometheus-community/charts

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: apps
spec:
  dependsOn:
    - name: external-secrets-secretstore
      namespace: flux-system
  path: ./kubernetes/apps/observability/release
  interval: 30m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: tibia
    namespace: flux-system

# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: kube-prometheus-ingress
#   namespace: apps
# spec:
#   dependsOn:
#     - name: kube-prometheus-stack
#   interval: 5m
#   path: ./kubernetes/apps/observability/ingress
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: tibia
#     namespace: flux-system
