apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  chart:
    spec:
      chart: authentik
      version: 2024.8.2
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: apps
  interval: 15m
  timeout: 10m
  releaseName: authentik
  values:
    authentik:
      log_level: info
      secret_key: "${AUTHENTIK_SECRET_KEY}"
      bootstrap:
        password: "${AUTHENTIK_BOOTSTRAP_PASSWORD}"
        token: "${AUTHENTIK_BOOTSTRAP_TOKEN}"
      postgresql:
        host: authentik-postgresql
        password: "${POSTGRESQL_PASSWORD}"
      redis:
        password: "${REDIS_PASSWORD}"

    server:
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"
          
    redis:
      enabled: true
      master:
        persistence:
          size: 1Gi
        
    postgresql:
      enabled: true
      auth:
        password: "${POSTGRESQL_PASSWORD}"

      # ingress:
      #   enabled: true
      #   ingressClassName: "traefik"
      #   hosts:
      #     - "authentik.mythbound.dev"
      #   tls: []
      #   paths:
      #     - path: /
      #       pathType: Prefix


      # readinessProbe:
      #   httpGet:
      #     path: "/-/health/ready/"
      #     port: "http"
      # livenessProbe:
      #   httpGet:
      #     path: "/-/health/live/"
      #     port: "http"
