apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb
  namespace: apps
spec:
  interval: 5m
  releaseName: mariadb
  chart:
    spec:
      chart: mariadb
      version: 11.3.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: apps
  values:
    image:
      # References: https://artifacthub.io/packages/helm/bitnami/mariadb
      registry: docker.io
      repository: bitnami/mariadb
      tag: 11.2.5
    auth:
      existingSecret: mariadb
      username: mariadb-user
      passwordKey: mariadb-password
      rootPasswordKey: mariadb-root-password
    primary:
      service:
        type: ClusterIP
      persistence:
        enabled: true
        size: 8Gi
    replica:
      replicaCount: 1
