apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb
  namespace: apps
spec:
  interval: 5m
  releaseName: mariadb
  chart:
    spec:
      chart: mariadb
      version: 11.3.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: apps
  values:
    image:
      # References: https://artifacthub.io/packages/helm/bitnami/mariadb
      registry: docker.io
      repository: bitnami/mariadb
      tag: 11.2.5
    auth:
      existingSecret: mariadb
    primary:
      extraEnvVarsSecret: mariadb 
      service:
        type: ClusterIP
      persistence:
        enabled: true
        size: 8Gi
    my_init_script.sh: |
      #!/bin/bash
      echo "MARIADB_USER: ${MARIADB_USER}"
      echo "MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}"
      /opt/bitnami/mariadb/bin/mysql -P 3306 -u${MARIADB_USER} -p"${MARIADB_ROOT_PASSWORD}" -e "create database forgottenserver";
    replica:
      replicaCount: 1
