---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-secrets
  namespace: apps
spec:
  dependsOn:
    - name: external-secrets-secretstore
      namespace: flux-system
  interval: 5m
  path: ./kubernetes/apps/mariadb/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: tibia
    namespace: flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: apps
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami
