apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
spec:
  selector:
    app.kubernetes.io/instance: traefik-kube-system
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
    name: dashboard
    nodePort: 31000
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: web
    nodePort: 32000
  - protocol: TCP
    port: 443
    targetPort: 8443
    name: websecure
    nodePort: 32443
  type: NodePort
