---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: myaac-external-secrets
  namespace: apps
spec:
  dependsOn:
    - name: external-secrets-secretstore
      namespace: flux-system
  interval: 5m
  path: ./kubernetes/apps/myaac/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: tibia
    namespace: flux-system
